/**
 * CFG Visualization Component
 * 
 * Renders a Context-Free Grammar as a beautifully formatted list of rules.
 * Features:
 * - Grouped rules by variable
 * - Color-coded variables and terminals
 * - Production highlighting based on current step
 * - KaTeX rendering for mathematical notation
 * - Smooth transition animations
 * - Origin tracking: hover to highlight related PDA transitions
 */

import { useMemo } from 'react';
import 'katex/dist/katex.min.css';
import { InlineMath } from 'react-katex';
import type { CFG, ProductionRule, PDA } from '../../types';

interface CFGVisualizerProps {
  cfg: CFG | null;
  highlightedRules?: string[];
  highlightedVariables?: string[];
  // Origin Tracker props
  hoveredOriginId?: string | null;
  onHoverOriginChange?: (id: string | null) => void;
  inputPda?: PDA | null;  // The input PDA (for PDA->CFG mode)
}

// Escape special LaTeX characters for display
function escapeLatex(str: string): string {
  return str
    .replace(/\\/g, '\\backslash ')
    .replace(/\$/g, '\\$')
    .replace(/_/g, '\\_')
    .replace(/#/g, '\\#')
    .replace(/%/g, '\\%')
    .replace(/&/g, '\\&')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/\^/g, '\\^{}')
    .replace(/~/g, '\\sim ');
}

// Group rules by their left-hand side variable
function groupRulesByVariable(rules: ProductionRule[]): Map<string, ProductionRule[]> {
  const groups = new Map<string, ProductionRule[]>();
  
  rules.forEach(rule => {
    if (!groups.has(rule.variable)) {
      groups.set(rule.variable, []);
    }
    groups.get(rule.variable)!.push(rule);
  });
  
  return groups;
}

export function CFGVisualizer({ 
  cfg, 
  highlightedRules = [], 
  highlightedVariables = [],
  hoveredOriginId = null,
  onHoverOriginChange,
  inputPda: _inputPda  // Reserved for future PDA cross-referencing
}: CFGVisualizerProps) {
  // Memoize grouped rules for performance
  const groupedRules = useMemo(() => {
    if (!cfg) return new Map<string, ProductionRule[]>();
    return groupRulesByVariable(cfg.productionRules);
  }, [cfg]);

  // Check if a rule should be highlighted via origin tracking
  const isOriginHighlighted = (rule: ProductionRule): boolean => {
    if (!hoveredOriginId) return false;
    // Highlight if this rule's ID matches the hovered ID
    if (rule.id === hoveredOriginId) return true;
    // Highlight if this rule's originId matches the hovered ID (rule generated by hovered transition)
    if (rule.originId === hoveredOriginId) return true;
    // Highlight if hovered rule has originId matching a PDA transition that shares originId with this rule
    return false;
  };

  // Handle rule hover
  const handleRuleHover = (rule: ProductionRule, isEntering: boolean) => {
    if (!onHoverOriginChange) return;
    if (isEntering) {
      // When hovering a rule, set hover to that rule's ID so PDA edges can highlight
      console.log('[CFG Origin Tracker] Hovering rule:', rule.id, 'originId:', rule.originId);
      onHoverOriginChange(rule.id);
    } else {
      onHoverOriginChange(null);
    }
  };

  // Sort variables with start symbol first
  const sortedVariables = useMemo(() => {
    if (!cfg) return [];
    const vars = Array.from(groupedRules.keys());
    return vars.sort((a, b) => {
      if (a === cfg.startSymbol) return -1;
      if (b === cfg.startSymbol) return 1;
      return a.localeCompare(b);
    });
  }, [cfg, groupedRules]);

  if (!cfg) {
    return (
      <div className="h-full flex items-center justify-center bg-gray-50 rounded-lg border-2 border-dashed border-gray-200">
        <div className="text-center text-gray-500">
          <svg className="w-12 h-12 mx-auto mb-3 text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <p className="font-medium">No CFG to visualize</p>
          <p className="text-sm">Convert a PDA or input a CFG to see the grammar</p>
        </div>
      </div>
    );
  }
  
  return (
    <div className="h-full flex flex-col bg-white rounded-lg border border-gray-200 overflow-hidden">
      {/* Header */}
      <div className="px-4 py-3 bg-gradient-to-r from-indigo-50 to-purple-50 border-b border-gray-200">
        <h3 className="text-sm font-semibold text-gray-800">Context-Free Grammar</h3>
        <div className="mt-1 flex flex-wrap gap-3 text-xs text-gray-600">
          <span>
            <InlineMath math={`V = \\{${cfg.variables.slice(0, 5).map(escapeLatex).join(', ')}${cfg.variables.length > 5 ? ', \\ldots' : ''}\\}`} />
          </span>
          <span>
            <InlineMath math={`\\Sigma = \\{${cfg.terminals.map(escapeLatex).join(', ')}\\}`} />
          </span>
          <span>
            <InlineMath math={`S = ${escapeLatex(cfg.startSymbol)}`} />
          </span>
        </div>
      </div>
      
      {/* Rules */}
      <div className="flex-1 overflow-auto p-4">
        <div className="space-y-3">
          {sortedVariables.map((variable) => {
            const rules = groupedRules.get(variable) || [];
            const isVariableHighlighted = highlightedVariables.includes(variable);
            
            return (
              <div 
                key={variable}
                className={`
                  p-3 rounded-lg transition-all duration-300 ease-in-out
                  ${isVariableHighlighted 
                    ? 'bg-amber-50 border-2 border-amber-300 shadow-md shadow-amber-100 scale-[1.02]' 
                    : 'bg-gray-50 border border-transparent hover:bg-gray-100'
                  }
                `}
              >
                <div className="flex items-start gap-2">
                  {/* Variable (LHS) */}
                  <span className={`
                    inline-flex items-center justify-center min-w-[2rem] h-7 px-2
                    rounded font-mono text-sm font-semibold transition-all duration-200
                    ${isVariableHighlighted 
                      ? 'bg-amber-300 text-amber-900 shadow-sm' 
                      : variable === cfg.startSymbol 
                        ? 'bg-indigo-200 text-indigo-900'
                        : 'bg-purple-100 text-purple-800'
                    }
                  `}>
                    {variable.length > 10 ? (
                      <span className="text-xs">{variable}</span>
                    ) : (
                      variable
                    )}
                  </span>
                  
                  {/* Arrow */}
                  <span className="text-gray-400 font-mono h-7 flex items-center">→</span>
                  
                  {/* Productions (RHS) */}
                  <div className="flex-1">
                    <div className="flex flex-wrap gap-x-3 gap-y-1">
                      {rules.map((rule, idx) => {
                        const isRuleHighlighted = highlightedRules.includes(rule.id);
                        const isOriginHovered = isOriginHighlighted(rule);
                        const showHighlight = isRuleHighlighted || isOriginHovered;
                        
                        return (
                          <span 
                            key={rule.id} 
                            className="flex items-center gap-1.5 h-7 cursor-pointer"
                            onMouseEnter={() => handleRuleHover(rule, true)}
                            onMouseLeave={() => handleRuleHover(rule, false)}
                          >
                            {idx > 0 && (
                              <span className="text-gray-400 font-mono">|</span>
                            )}
                            <span 
                              className={`
                                font-mono text-sm px-1.5 py-0.5 rounded transition-all duration-200
                                ${showHighlight 
                                  ? isOriginHovered && !isRuleHighlighted
                                    ? 'bg-blue-100 text-blue-900 font-semibold shadow-sm ring-2 ring-blue-400'
                                    : 'bg-amber-200 text-amber-900 font-semibold shadow-sm ring-2 ring-amber-300' 
                                  : 'text-gray-700 hover:bg-gray-100'
                                }
                              `}
                            >
                              {rule.production ? (
                                <ProductionDisplay 
                                  production={rule.production} 
                                  terminals={cfg.terminals}
                                  isHighlighted={isRuleHighlighted}
                                />
                              ) : (
                                <span className="text-purple-600 italic">ε</span>
                              )}
                            </span>
                          </span>
                        );
                      })}
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
        
        {/* Stats */}
        <div className="mt-4 pt-4 border-t border-gray-200">
          <div className="flex gap-4 text-xs text-gray-500">
            <span className="flex items-center gap-1">
              <span className="w-2 h-2 rounded-full bg-purple-300"></span>
              {cfg.variables.length} variables
            </span>
            <span className="flex items-center gap-1">
              <span className="w-2 h-2 rounded-full bg-emerald-300"></span>
              {cfg.terminals.length} terminals
            </span>
            <span className="flex items-center gap-1">
              <span className="w-2 h-2 rounded-full bg-indigo-300"></span>
              {cfg.productionRules.length} production rules
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}

// Helper component to display production with color-coded terminals/variables
function ProductionDisplay({ 
  production, 
  terminals, 
  isHighlighted 
}: { 
  production: string; 
  terminals: string[];
  isHighlighted: boolean;
}) {
  // Handle triple notation [p, X, q]
  if (production.includes('[') && production.includes(',')) {
    // Split by spaces and render each triple
    const parts = production.split(/\s+/).filter(p => p);
    return (
      <span className="inline-flex items-center gap-1">
        {parts.map((part, idx) => {
          if (part.startsWith('[') && part.endsWith(']')) {
            // Triple variable
            return (
              <span 
                key={idx} 
                className={`px-1 rounded ${isHighlighted ? '' : 'bg-purple-50'}`}
              >
                {part}
              </span>
            );
          } else if (terminals.includes(part)) {
            // Terminal
            return (
              <span 
                key={idx} 
                className={`text-emerald-600 font-semibold ${isHighlighted ? '' : ''}`}
              >
                {part}
              </span>
            );
          } else {
            return <span key={idx}>{part}</span>;
          }
        })}
      </span>
    );
  }
  
  // Simple production - color-code each character
  const chars = production.split('');
  return (
    <span>
      {chars.map((char, idx) => {
        if (char === 'ε') {
          return <span key={idx} className="text-purple-600 italic">ε</span>;
        } else if (terminals.includes(char)) {
          return (
            <span key={idx} className="text-emerald-600 font-semibold">
              {char}
            </span>
          );
        } else if (char.match(/[A-Z]/)) {
          return (
            <span key={idx} className="text-purple-700">
              {char}
            </span>
          );
        }
        return <span key={idx}>{char}</span>;
      })}
    </span>
  );
}
