/**
 * PDA Graph Visualization Component
 * 
 * Renders a PDA as an interactive directed graph using React Flow.
 * Features:
 * - Nodes as states (circles)
 * - Edges as transitions with labels
 * - Auto-layout using dagre
 * - Self-loop handling with custom bezier curves
 * - Multiple edge handling with bezier offsets
 * - Step highlighting with smooth animations
 * - Export to PNG/SVG
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  ReactFlow,
  Background,
  Controls,
  MiniMap,
  useNodesState,
  useEdgesState,
  MarkerType,
  Position,
  Handle,
  BaseEdge,
  EdgeLabelRenderer,
  getBezierPath,
} from '@xyflow/react';
import type { Node, Edge, NodeProps, EdgeProps } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import dagre from '@dagrejs/dagre';
import toast from 'react-hot-toast';
import type { PDA, CFG } from '../../types';

/**
 * Converts React Flow nodes and edges to LaTeX TikZ automata code
 */
function generateTikZCode(nodes: Node[], edges: Edge[]): string {
  const lines: string[] = [];
  
  // TikZ preamble
  lines.push('% TikZ Automata - Generated by CFG ↔ PDA Converter');
  lines.push('% Add to preamble: \\usepackage{tikz}');
  lines.push('% Add to preamble: \\usetikzlibrary{automata,positioning,arrows.meta}');
  lines.push('');
  lines.push('\\begin{tikzpicture}[');
  lines.push('  ->,');
  lines.push('  >=Stealth,');
  lines.push('  node distance=3cm,');
  lines.push('  every state/.style={thick, fill=gray!10},');
  lines.push('  initial text={}');
  lines.push(']');
  lines.push('');
  
  // Sort nodes by position for better layout
  const sortedNodes = [...nodes].sort((a, b) => {
    const xDiff = (a.position?.x || 0) - (b.position?.x || 0);
    if (Math.abs(xDiff) > 50) return xDiff;
    return (a.position?.y || 0) - (b.position?.y || 0);
  });
  
  // Generate node definitions
  lines.push('  % States');
  sortedNodes.forEach((node, idx) => {
    const isStart = node.data?.isStart as boolean;
    const isAccept = node.data?.isAccept as boolean;
    const label = escapeLatex(node.data?.label as string || node.id);
    
    // Build state options
    const options: string[] = ['state'];
    if (isStart) options.push('initial');
    if (isAccept) options.push('accepting');
    
    // Position relative to previous node
    let positioning = '';
    if (idx > 0) {
      const prevNode = sortedNodes[idx - 1];
      const dx = (node.position?.x || 0) - (prevNode.position?.x || 0);
      const dy = (node.position?.y || 0) - (prevNode.position?.y || 0);
      
      if (Math.abs(dx) > Math.abs(dy)) {
        positioning = dx > 0 ? `right of=${escapeLatex(prevNode.id)}` : `left of=${escapeLatex(prevNode.id)}`;
      } else {
        positioning = dy > 0 ? `below of=${escapeLatex(prevNode.id)}` : `above of=${escapeLatex(prevNode.id)}`;
      }
      options.push(positioning);
    }
    
    const nodeId = escapeLatex(node.id);
    lines.push(`  \\node[${options.join(', ')}] (${nodeId}) {$${label}$};`);
  });
  
  lines.push('');
  lines.push('  % Transitions');
  
  // Group edges by source-target pair
  const edgeGroups = new Map<string, Edge[]>();
  edges.forEach(edge => {
    const key = `${edge.source}->${edge.target}`;
    if (!edgeGroups.has(key)) {
      edgeGroups.set(key, []);
    }
    edgeGroups.get(key)!.push(edge);
  });
  
  // Generate edge definitions
  edgeGroups.forEach((groupedEdges, key) => {
    const [source, target] = key.split('->');
    const isSelfLoop = source === target;
    
    // Combine labels for edges between same nodes
    const labels = groupedEdges.map(e => escapeLatex(e.label as string || '')).filter(l => l);
    const combinedLabel = labels.join(', ');
    
    const srcId = escapeLatex(source);
    const tgtId = escapeLatex(target);
    
    if (isSelfLoop) {
      lines.push(`  \\path (${srcId}) edge[loop above] node {$${combinedLabel}$} (${tgtId});`);
    } else {
      // Check for bidirectional edges
      const reverseKey = `${target}->${source}`;
      const hasBidirectional = edgeGroups.has(reverseKey);
      
      if (hasBidirectional && source < target) {
        // Only render once for bidirectional, use bend
        lines.push(`  \\path (${srcId}) edge[bend left=15] node[above] {$${combinedLabel}$} (${tgtId});`);
      } else if (hasBidirectional && source > target) {
        lines.push(`  \\path (${srcId}) edge[bend left=15] node[below] {$${combinedLabel}$} (${tgtId});`);
      } else {
        lines.push(`  \\path (${srcId}) edge node[above] {$${combinedLabel}$} (${tgtId});`);
      }
    }
  });
  
  lines.push('');
  lines.push('\\end{tikzpicture}');
  
  return lines.join('\n');
}

/**
 * Escape special LaTeX characters
 */
function escapeLatex(str: string): string {
  if (!str) return '';
  return str
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/_/g, '\\_')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/%/g, '\\%')
    .replace(/&/g, '\\&')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/\^/g, '\\^{}')
    .replace(/~/g, '\\~{}')
    .replace(/ε/g, '\\varepsilon');
}

/**
 * LaTeX Export Modal Component
 */
function LaTeXModal({ 
  isOpen, 
  onClose, 
  latexCode 
}: { 
  isOpen: boolean; 
  onClose: () => void; 
  latexCode: string;
}) {
  if (!isOpen) return null;
  
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(latexCode);
      toast.success('Copied to clipboard!');
    } catch (err) {
      console.error('Copy failed:', err);
      toast.error('Failed to copy');
    }
  };
  
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/50 backdrop-blur-sm"
        onClick={onClose}
      />
      
      {/* Modal */}
      <div className="relative bg-white rounded-xl shadow-2xl w-full max-w-2xl mx-4 max-h-[80vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-indigo-100 rounded-lg flex items-center justify-center">
              <svg className="w-5 h-5 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
              </svg>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-gray-900">LaTeX TikZ Code</h3>
              <p className="text-sm text-gray-500">Copy and paste into your LaTeX document</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        
        {/* Code Area */}
        <div className="flex-1 overflow-auto p-4">
          <pre className="bg-gray-900 text-gray-100 rounded-lg p-4 text-sm font-mono overflow-x-auto whitespace-pre">
            {latexCode}
          </pre>
        </div>
        
        {/* Footer */}
        <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-gray-200 bg-gray-50 rounded-b-xl">
          <button
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-900 
              hover:bg-gray-100 rounded-lg transition-colors"
          >
            Close
          </button>
          <button
            onClick={handleCopy}
            className="inline-flex items-center gap-2 px-4 py-2 text-sm font-semibold 
              text-white bg-indigo-600 hover:bg-indigo-700 rounded-lg transition-colors shadow-sm"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
            Copy to Clipboard
          </button>
        </div>
      </div>
    </div>
  );
}

interface PDAGraphProps {
  pda: PDA | null;
  highlightedStates?: string[];
  highlightedTransitions?: string[];
  onExport?: (format: 'png' | 'svg') => void;
  // Origin Tracker props
  hoveredOriginId?: string | null;
  onHoverOriginChange?: (id: string | null) => void;
  inputCfg?: CFG | null;  // The input CFG (for CFG->PDA mode)
}

// Custom node component for PDA states
function StateNode({ data }: NodeProps) {
  const isStart = data.isStart as boolean;
  const isAccept = data.isAccept as boolean;
  const isHighlighted = data.isHighlighted as boolean;
  const label = data.label as string;
  
  return (
    <div className="relative">
      {/* Start state arrow */}
      {isStart && (
        <div className="absolute -left-8 top-1/2 -translate-y-1/2">
          <svg width="24" height="24" viewBox="0 0 24 24">
            <path 
              d="M4 12 L20 12 M14 6 L20 12 L14 18" 
              stroke="#6366f1" 
              strokeWidth="2" 
              fill="none"
            />
          </svg>
        </div>
      )}
      
      {/* State circle */}
      <div 
        className={`
          w-14 h-14 rounded-full flex items-center justify-center
          border-2 transition-all duration-300
          ${isHighlighted 
            ? 'bg-amber-100 border-amber-500 shadow-lg shadow-amber-200 scale-110' 
            : 'bg-white border-gray-300 hover:border-gray-400'
          }
          ${isAccept ? 'ring-2 ring-offset-2 ring-gray-400' : ''}
        `}
      >
        <span className={`text-sm font-medium transition-colors duration-200 ${isHighlighted ? 'text-amber-800' : 'text-gray-700'}`}>
          {label}
        </span>
      </div>
      
      {/* Handles for edges - hidden visually but functional for routing */}
      <Handle type="target" position={Position.Left} className="!opacity-0 !w-2 !h-2" />
      <Handle type="source" position={Position.Right} className="!opacity-0 !w-2 !h-2" />
      <Handle type="target" position={Position.Top} id="top" className="!opacity-0 !w-2 !h-2" />
      <Handle type="source" position={Position.Bottom} id="bottom" className="!opacity-0 !w-2 !h-2" />
      {/* Additional handles for self-loops */}
      <Handle type="source" position={Position.Top} id="loop-out" className="!opacity-0 !w-2 !h-2 !left-[70%]" />
      <Handle type="target" position={Position.Top} id="loop-in" className="!opacity-0 !w-2 !h-2 !left-[30%]" />
    </div>
  );
}

/**
 * Custom Self-Loop Edge Component
 * Renders a beautiful curved self-loop above the node
 */
function SelfLoopEdge({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  label,
  data,
  markerEnd,
}: EdgeProps) {
  const isHighlighted = data?.isHighlighted as boolean;
  const loopOffset = (data?.loopIndex as number || 0) * 25;
  
  // Create a self-loop path using cubic bezier curves
  const loopHeight = 50 + loopOffset;
  const loopWidth = 35;
  
  // The path starts from source, goes up in a loop, and returns to target
  const path = `
    M ${sourceX} ${sourceY}
    C ${sourceX + loopWidth} ${sourceY - loopHeight},
      ${targetX - loopWidth} ${targetY - loopHeight},
      ${targetX} ${targetY}
  `;
  
  // Calculate label position (top of the loop)
  const labelX = (sourceX + targetX) / 2;
  const labelY = sourceY - loopHeight - 5;
  
  return (
    <>
      <BaseEdge
        id={id}
        path={path}
        markerEnd={markerEnd}
        style={{
          stroke: isHighlighted ? '#f59e0b' : '#6b7280',
          strokeWidth: isHighlighted ? 2.5 : 1.5,
          transition: 'stroke 0.2s, stroke-width 0.2s',
        }}
        className={isHighlighted ? 'animate-pulse' : ''}
      />
      {label && (
        <EdgeLabelRenderer>
          <div
            style={{
              position: 'absolute',
              transform: `translate(-50%, -50%) translate(${labelX}px, ${labelY}px)`,
              pointerEvents: 'all',
            }}
            className="nodrag nopan"
          >
            <div
              className={`
                px-2 py-1 rounded text-xs font-mono whitespace-nowrap
                transition-all duration-200
                ${isHighlighted 
                  ? 'bg-amber-100 text-amber-900 font-semibold shadow-md' 
                  : 'bg-gray-50 text-gray-700 border border-gray-200'
                }
              `}
            >
              {label as string}
            </div>
          </div>
        </EdgeLabelRenderer>
      )}
    </>
  );
}

/**
 * Custom Bezier Edge with offset support for multiple edges
 * between the same two nodes
 */
function OffsetBezierEdge({
  id,
  sourceX,
  sourceY,
  targetX,
  targetY,
  sourcePosition,
  targetPosition,
  label,
  data,
  markerEnd,
}: EdgeProps) {
  const isHighlighted = data?.isHighlighted as boolean;
  const offset = (data?.offset as number) || 0;
  
  // Calculate curved path with offset
  const [edgePath, labelX, labelY] = getBezierPath({
    sourceX,
    sourceY: sourceY + offset,
    targetX,
    targetY: targetY + offset,
    sourcePosition,
    targetPosition,
    curvature: 0.25 + Math.abs(offset) * 0.005, // More curve for offset edges
  });
  
  return (
    <>
      <BaseEdge
        id={id}
        path={edgePath}
        markerEnd={markerEnd}
        style={{
          stroke: isHighlighted ? '#f59e0b' : '#6b7280',
          strokeWidth: isHighlighted ? 2.5 : 1.5,
          transition: 'stroke 0.2s, stroke-width 0.2s',
        }}
        className={isHighlighted ? 'animate-pulse' : ''}
      />
      {label && (
        <EdgeLabelRenderer>
          <div
            style={{
              position: 'absolute',
              transform: `translate(-50%, -50%) translate(${labelX}px, ${labelY + offset}px)`,
              pointerEvents: 'all',
            }}
            className="nodrag nopan"
          >
            <div
              className={`
                px-2 py-1 rounded text-xs font-mono whitespace-nowrap
                transition-all duration-200
                ${isHighlighted 
                  ? 'bg-amber-100 text-amber-900 font-semibold shadow-md' 
                  : 'bg-gray-50 text-gray-700 border border-gray-200'
                }
              `}
            >
              {label as string}
            </div>
          </div>
        </EdgeLabelRenderer>
      )}
    </>
  );
}

const nodeTypes = {
  stateNode: StateNode,
};

const edgeTypes = {
  selfLoop: SelfLoopEdge,
  offsetBezier: OffsetBezierEdge,
};

// Apply dagre layout to nodes and edges
function getLayoutedElements(
  nodes: Node[],
  edges: Edge[],
  direction: 'TB' | 'LR' = 'LR'
): { nodes: Node[]; edges: Edge[] } {
  const dagreGraph = new dagre.graphlib.Graph();
  dagreGraph.setDefaultEdgeLabel(() => ({}));
  
  const nodeWidth = 80;
  const nodeHeight = 80;
  
  dagreGraph.setGraph({ 
    rankdir: direction,
    nodesep: 80,
    ranksep: 120,
    marginx: 50,
    marginy: 50,
  });
  
  nodes.forEach((node) => {
    dagreGraph.setNode(node.id, { width: nodeWidth, height: nodeHeight });
  });
  
  edges.forEach((edge) => {
    dagreGraph.setEdge(edge.source, edge.target);
  });
  
  dagre.layout(dagreGraph);
  
  const layoutedNodes = nodes.map((node) => {
    const nodeWithPosition = dagreGraph.node(node.id);
    return {
      ...node,
      position: {
        x: nodeWithPosition.x - nodeWidth / 2,
        y: nodeWithPosition.y - nodeHeight / 2,
      },
    };
  });
  
  return { nodes: layoutedNodes, edges };
}

// Format transition label
function formatTransitionLabel(
  inputSymbol: string | null,
  poppedSymbol: string,
  pushedSymbols: string | null
): string {
  const input = inputSymbol || 'ε';
  const push = pushedSymbols || 'ε';
  return `${input}, ${poppedSymbol} → ${push}`;
}

// Group transitions by source-target pair for edge offset calculation
function groupTransitions(pda: PDA): Map<string, typeof pda.transitions> {
  const groups = new Map<string, typeof pda.transitions>();
  
  pda.transitions.forEach(t => {
    const key = `${t.currentState}->${t.nextState}`;
    if (!groups.has(key)) {
      groups.set(key, []);
    }
    groups.get(key)!.push(t);
  });
  
  return groups;
}

export function PDAGraph({ 
  pda, 
  highlightedStates = [], 
  highlightedTransitions = [],
  hoveredOriginId = null,
  onHoverOriginChange
}: PDAGraphProps) {
  const [nodes, setNodes, onNodesChange] = useNodesState<Node>([]);
  const [edges, setEdges, onEdgesChange] = useEdgesState<Edge>([]);
  const layoutAppliedRef = useRef<string | null>(null); // Track which PDA has been laid out
  
  // Memoize node types and edge types to prevent re-renders
  const memoizedNodeTypes = useMemo(() => nodeTypes, []);
  const memoizedEdgeTypes = useMemo(() => edgeTypes, []);
  
  // Generate a stable key for the PDA structure (for layout caching)
  const pdaKey = useMemo(() => {
    if (!pda) return null;
    return JSON.stringify({
      states: pda.states,
      transitions: pda.transitions.map(t => ({
        from: t.currentState,
        to: t.nextState,
      })),
    });
  }, [pda]);

  // Handle edge hover for origin tracking
  const handleEdgeMouseEnter = useCallback((_event: React.MouseEvent, edge: Edge) => {
    if (onHoverOriginChange) {
      onHoverOriginChange(edge.id);
    }
  }, [onHoverOriginChange]);

  const handleEdgeMouseLeave = useCallback(() => {
    if (onHoverOriginChange) {
      onHoverOriginChange(null);
    }
  }, [onHoverOriginChange]);
  
  // Build and layout graph only when PDA structure changes
  useEffect(() => {
    if (!pda || pdaKey === layoutAppliedRef.current) return;
    
    // Create nodes from states
    const newNodes: Node[] = pda.states.map((state) => ({
      id: state,
      type: 'stateNode',
      position: { x: 0, y: 0 }, // Will be set by layout
      data: {
        label: state,
        isStart: state === pda.startState,
        isAccept: pda.acceptStates.includes(state),
        isHighlighted: highlightedStates.includes(state),
      },
    }));
    
    // Group transitions and create edges with proper types
    const transitionGroups = groupTransitions(pda);
    const newEdges: Edge[] = [];
    
    // Also track reverse edges for bidirectional offset
    const bidirectionalPairs = new Set<string>();
    transitionGroups.forEach((_, key) => {
      const [source, target] = key.split('->');
      const reverseKey = `${target}->${source}`;
      if (transitionGroups.has(reverseKey) && source !== target) {
        bidirectionalPairs.add([source, target].sort().join('<->'));
      }
    });
    
    transitionGroups.forEach((transitions, key) => {
      const isSelfLoop = transitions[0].currentState === transitions[0].nextState;
      const [source, target] = key.split('->');
      const isBidirectional = bidirectionalPairs.has([source, target].sort().join('<->'));
      
      transitions.forEach((t, idx) => {
        const isHighlighted = highlightedTransitions.includes(t.id);
        const label = formatTransitionLabel(t.inputSymbol, t.poppedSymbol, t.pushedSymbols);
        
        // Debug: Log transition originId
        if (t.originId) {
          console.log('[PDA Graph] Creating edge from transition:', t.id, 'with originId:', t.originId);
        }
        
        // Calculate offset for multiple edges between same nodes
        const totalEdges = transitions.length;
        let offsetAmount = 0;
        
        if (totalEdges > 1) {
          offsetAmount = (idx - (totalEdges - 1) / 2) * 35;
        } else if (isBidirectional && !isSelfLoop) {
          // Offset single edges in bidirectional pairs
          offsetAmount = source < target ? -20 : 20;
        }
        
        if (isSelfLoop) {
          // Use custom self-loop edge type
          const edge: Edge = {
            id: t.id,
            source: t.currentState,
            target: t.nextState,
            type: 'selfLoop',
            sourceHandle: 'loop-out',
            targetHandle: 'loop-in',
            label,
            animated: isHighlighted, // Animate active edges
            data: {
              isHighlighted,
              loopIndex: idx, // For stacking multiple self-loops
              originId: t.originId, // For origin tracking
            },
            markerEnd: {
              type: MarkerType.ArrowClosed,
              color: isHighlighted ? '#f59e0b' : '#6b7280',
              width: 16,
              height: 16,
            },
          };
          newEdges.push(edge);
        } else {
          // Use custom offset bezier edge type
          const edge: Edge = {
            id: t.id,
            source: t.currentState,
            target: t.nextState,
            type: 'offsetBezier',
            label,
            animated: isHighlighted, // Animate active edges
            data: {
              isHighlighted,
              offset: offsetAmount,
              originId: t.originId, // For origin tracking
            },
            markerEnd: {
              type: MarkerType.ArrowClosed,
              color: isHighlighted ? '#f59e0b' : '#6b7280',
              width: 16,
              height: 16,
            },
          };
          newEdges.push(edge);
        }
      });
    });
    
    // Apply dagre layout
    const { nodes: layoutedNodes, edges: layoutedEdges } = getLayoutedElements(
      newNodes,
      newEdges
    );
    
    setNodes(layoutedNodes);
    setEdges(layoutedEdges);
    layoutAppliedRef.current = pdaKey;
  }, [pda, pdaKey, setNodes, setEdges]); // Note: Don't include highlightedStates/Transitions here
  
  // Update highlighting WITHOUT re-running layout (step-wise visualization)
  useEffect(() => {
    if (!pda || !layoutAppliedRef.current) return;
    
    // Update node highlighting
    setNodes((currentNodes) =>
      currentNodes.map((node) => ({
        ...node,
        data: {
          ...node.data,
          isHighlighted: highlightedStates.includes(node.id),
        },
      }))
    );
    
    // Update edge highlighting and animation
    setEdges((currentEdges) =>
      currentEdges.map((edge) => {
        const isHighlighted = highlightedTransitions.includes(edge.id);
        return {
          ...edge,
          animated: isHighlighted, // Animate only active edges
          data: {
            ...edge.data,
            isHighlighted,
          },
          markerEnd: {
            type: MarkerType.ArrowClosed,
            color: isHighlighted ? '#f59e0b' : '#6b7280',
            width: 16,
            height: 16,
          },
        };
      })
    );
  }, [highlightedStates, highlightedTransitions, pda, setNodes, setEdges]);

  // Update edge styling based on hoveredOriginId (for origin tracking)
  useEffect(() => {
    if (!pda) return;
    
    console.log('[PDA Origin Tracker] hoveredOriginId:', hoveredOriginId);
    
    setEdges((currentEdges) =>
      currentEdges.map((edge) => {
        const isHighlighted = highlightedTransitions.includes(edge.id);
        // Check if this edge should be origin-highlighted
        const isOriginHovered = hoveredOriginId !== null && (
          edge.id === hoveredOriginId ||
          edge.data?.originId === hoveredOriginId
        );
        
        if (isOriginHovered) {
          console.log('[PDA Origin Tracker] Edge highlighted:', edge.id, 'originId:', edge.data?.originId);
        }
        
        // Determine color: origin hover takes precedence over step highlight
        let strokeColor = '#6b7280'; // default gray
        if (isOriginHovered) {
          strokeColor = '#3b82f6'; // bright blue for origin tracking
        } else if (isHighlighted) {
          strokeColor = '#f59e0b'; // amber for step highlight
        }
        
        return {
          ...edge,
          animated: isHighlighted || isOriginHovered,
          data: {
            ...edge.data,
            isHighlighted,
            isOriginHovered,
          },
          style: {
            ...edge.style,
            stroke: strokeColor,
            strokeWidth: isOriginHovered ? 3 : isHighlighted ? 2.5 : 2,
            transition: 'stroke 0.2s ease, stroke-width 0.2s ease',
          },
          markerEnd: {
            type: MarkerType.ArrowClosed,
            color: strokeColor,
            width: 16,
            height: 16,
          },
        };
      })
    );
  }, [hoveredOriginId, highlightedTransitions, pda, setEdges]);
  
  if (!pda) {
    return (
      <div className="h-full flex items-center justify-center bg-gray-50 rounded-lg border-2 border-dashed border-gray-200">
        <div className="text-center text-gray-500">
          <svg className="w-12 h-12 mx-auto mb-3 text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z" />
          </svg>
          <p className="font-medium">No PDA to visualize</p>
          <p className="text-sm">Convert a CFG or input a PDA to see the graph</p>
        </div>
      </div>
    );
  }
  
  return (
    <div className="h-full w-full">
      <ReactFlow
        nodes={nodes}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        nodeTypes={memoizedNodeTypes}
        edgeTypes={memoizedEdgeTypes}
        onEdgeMouseEnter={handleEdgeMouseEnter}
        onEdgeMouseLeave={handleEdgeMouseLeave}
        fitView
        fitViewOptions={{ padding: 0.4 }}
        minZoom={0.2}
        maxZoom={2.5}
        proOptions={{ hideAttribution: true }}
        defaultEdgeOptions={{
          type: 'offsetBezier',
        }}
      >
        <Background color="#e5e7eb" gap={16} size={1} />
        <Controls 
          className="!bg-white !border-gray-200 !shadow-sm !rounded-lg"
          showZoom={true}
          showFitView={true}
          showInteractive={false}
        />
        <MiniMap 
          nodeColor={(node) => {
            if (node.data?.isHighlighted) return '#fbbf24';
            if (node.data?.isStart) return '#818cf8';
            if (node.data?.isAccept) return '#34d399';
            return '#d1d5db';
          }}
          className="!bg-white !border-gray-200 !rounded-lg !shadow-sm"
          maskColor="rgba(0, 0, 0, 0.1)"
          pannable
          zoomable
        />
      </ReactFlow>
    </div>
  );
}

// Export button component that can be used outside the graph
export function ExportButton({ 
  onClick, 
  format 
}: { 
  onClick: () => void; 
  format: 'png' | 'svg';
}) {
  return (
    <button
      onClick={onClick}
      className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-gray-600 
        bg-white border border-gray-200 rounded-lg hover:bg-gray-50 hover:border-gray-300 
        transition-colors shadow-sm"
    >
      <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
      </svg>
      {format.toUpperCase()}
    </button>
  );
}

// Wrapper with download functionality
interface PDAGraphWithExportProps extends PDAGraphProps {
  containerRef?: React.RefObject<HTMLDivElement | null>;
}

export function PDAGraphWithExport(props: PDAGraphWithExportProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [showLatexModal, setShowLatexModal] = useState(false);
  const [latexCode, setLatexCode] = useState('');
  
  const handleExport = useCallback(async (format: 'png' | 'svg') => {
    if (!containerRef.current) return;
    
    const flowElement = containerRef.current.querySelector('.react-flow') as HTMLElement;
    if (!flowElement) return;
    
    try {
      // Dynamic import for html-to-image (only when needed)
      const { toPng, toSvg } = await import('html-to-image');
      
      const downloadImage = (dataUrl: string, extension: string) => {
        const link = document.createElement('a');
        link.download = `pda-graph.${extension}`;
        link.href = dataUrl;
        link.click();
      };
      
      if (format === 'png') {
        const dataUrl = await toPng(flowElement, {
          backgroundColor: '#ffffff',
          quality: 1,
          pixelRatio: 2,
        });
        downloadImage(dataUrl, 'png');
      } else {
        const dataUrl = await toSvg(flowElement, {
          backgroundColor: '#ffffff',
        });
        downloadImage(dataUrl, 'svg');
      }
    } catch (err) {
      console.error('Export failed:', err);
    }
  }, []);
  
  const handleExportLatex = useCallback(() => {
    if (!props.pda) return;
    
    // Generate nodes and edges from PDA for LaTeX generation
    const pda = props.pda;
    const nodes: Node[] = pda.states.map((state, idx) => ({
      id: state,
      type: 'stateNode',
      position: { x: idx * 150, y: 0 }, // Simple left-to-right layout for position hints
      data: {
        label: state,
        isStart: state === pda.startState,
        isAccept: pda.acceptStates.includes(state),
      },
    }));
    
    // Create edges from transitions
    const edges: Edge[] = pda.transitions.map((t) => ({
      id: t.id,
      source: t.currentState,
      target: t.nextState,
      label: formatTransitionLabel(t.inputSymbol, t.poppedSymbol, t.pushedSymbols),
    }));
    
    const code = generateTikZCode(nodes, edges);
    setLatexCode(code);
    setShowLatexModal(true);
  }, [props.pda]);
  
  return (
    <div ref={containerRef} className="h-full w-full relative">
      <PDAGraph {...props} />
      {props.pda && (
        <div className="absolute top-2 right-2 flex gap-2 z-10">
          <button
            onClick={handleExportLatex}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-gray-600 
              bg-white border border-gray-200 rounded-lg hover:bg-gray-50 hover:border-gray-300 
              transition-colors shadow-sm"
            title="Export to LaTeX TikZ"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
            </svg>
            LaTeX
          </button>
          <ExportButton onClick={() => handleExport('png')} format="png" />
          <ExportButton onClick={() => handleExport('svg')} format="svg" />
        </div>
      )}
      <LaTeXModal 
        isOpen={showLatexModal} 
        onClose={() => setShowLatexModal(false)} 
        latexCode={latexCode}
      />
    </div>
  );
}
